-- db			statecapitols
-- table			statecaps
-- Number of columns	11

CREATE TABLE `statecapitols`.`statecaps` (`id` SMALLINT NOT NULL AUTO_INCREMENT COMMENT 'index' , `State_name` TEXT NOT NULL COMMENT 'state name' , `Abbr` TEXT NOT NULL COMMENT 'abbreviation' , `Capital` TEXT NOT NULL COMMENT 'state capital' , `Most_pop` TEXT NOT NULL COMMENT 'largest city' , `Population` INT NOT NULL COMMENT 'Most populous city', `2nd_most_pop` TEXT NOT NULL COMMENT 'largest city' , `2nd_most_pop_pops` INT NOT NULL COMMENT '2nd most populous city', `3rd_most_pop` TEXT NOT NULL COMMENT 'largest city' , `3rd_most_pop_pops` INT NOT NULL COMMENT '3rd most populous city', PRIMARY KEY (`id`)) ENGINE = InnoDB COMMENT = 'USA state stats incl capitols';

ALTER TABLE `statecaps` ADD INDEX(`id`);



INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Alabama','AL','Montgomery','Huntsville','225564','Birmingham','196644','Montgomery','195287');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Alaska','AK','Juneau','Anchorage','286075','Fairbanks','31856','Juneau','31555');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Arizona','AZ','Phoenix','Phoenix','1650070','Tucson','547239','Mesa','511648');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Arkansas','AR','Little Rock','Little Rock','203842','Fayetteville','101680','Fort Smith','89770');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('California','CA','Sacramento','Los Angeles','3820914','San Diego','1388320','San Jose','969655');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Colorado','CO','Denver','Denver','716577','Colorado Springs','488664','Aurora','395052');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Connecticut','CT','Hartford','Bridgeport','148028','Stamford','136226','New Haven','135319');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Delaware','DE','Dover','Wilmington','71675','Dover','39894','Newark','30169');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Florida','FL','Tallahassee','Jacksonville','985843','Miami','455924','Tampa','403364');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Georgia','GA','Atlanta','Atlanta','510823','Columbus','201877','Augusta','200884');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Hawaii','HI','Honolulu','Honolulu','350964','East Honolulu ','50922','Pearl City','45295');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Idaho','ID','Boise','Boise','235421','Meridian','134801','Nampa','114268');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Illinois','IL','Springfield','Chicago','2664452','Aurora','177563','Joliet','150489');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Indiana','IN','Indianapolis','Indianapolis','879293','Fort Wayne','269994','Evansville','115332');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Iowa','IA','Des Moines','Des Moines','210381','Cedar Rapids','135958','Davenport','100354');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Kansas','KS','Topeka','Wichita','396119','Overland Park','197089','Kansas City','152933');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Kentucky','KY','Frankfort','Louisville','622981','Lexington','320154','Bowling Green','76212');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Louisiana','LA','Baton Rouge','New Orleans','364136','Baton Rouge','219573','Shreveport','177959');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Maine','ME','Augusta','Portland','69104','Lewiston','38404','Bangor','31628');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Maryland','MD','Annapolis','Baltimore','565239','Frederick','85793','Gaithersburg','69563');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Massachusetts','MA','Boston','Boston','653833','Worcester','207621','Springfield','153672');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Michigan','MI','Lansing','Detroit','633218','Grand Rapids','196608','Warren','136655');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Minnesota','MN','Saint Paul','Minneapolis','425115','Saint Paul','303820','Rochester','122413');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Mississippi','MS','Jackson','Jackson','143709','Gulfport','72823','Southaven','56851');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Missouri','MO','Jefferson City','Kansas City','510704','Saint Louis','281754','Springfield','170188');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Montana','MT','Helena','Billings','120864','Missoula','77757','Great Falls','60422');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Nebraska','NE','Lincoln','Omaha','483335','Lincoln','294757','Bellevue','63922');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Nevada','NV','Carson City','Las Vegas','660929','Henderson','337305','North Las Vegas','284771');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('New Hampshire','NH','Concord','Manchester','115474','Nashua','91003','Concord','44629');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('New Jersey','NJ','Trenton','Newark','304960','Jersey City','291657','Paterson','156452');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('New Mexico','NM','Santa Fe','Albuquerque','560274','Las Cruces','114892','Rio Rancho','110660');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('New York','NY','Albany','New York','8258035','Buffalo','274678','Yonkers','207657');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('North Carolina','NC','Raleigh','Charlotte','911311','Raleigh','482295','Greensboro','302296');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('North Dakota','ND','Bismarck','Fargo','133188','Bismarck','75092','Grand Forks','58921');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Ohio','OH','Columbus','Columbus','913175','Cleveland','362656','Cincinnati','311097');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Oklahoma','OK','Oklahoma City','Oklahoma City','702767','Tulsa','411894','Norman','130046');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Oregon','OR','Salem','Portland','630498','Eugene','177899','Salem','177432');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Pennsylvania','PA','Harrisburg','Philadelphia','1550542','Pittsburgh','303255','Allentown','124880');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Rhode Island','RI','Providence','Providence','190792','Warwick','82999','Cranston','82632');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('South Carolina','SC','Columbia','Charleston','155369','Columbia','142416','North Charleston','121469');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('South Dakota','SD','Pierre','Sioux Falls','206410','Rapid City','79404','Aberdeen','28110');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Tennessee','TN','Nashville','Nashville','687788','Memphis','618639','Knoxville','198162');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Texas','TX','Austin','Houston','2314157','San Antonio','1495295','Dallas','1302868');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Utah','UT','Salt Lake City','Salt Lake City','209593','West Valley City','134470','West Jordan','114908');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Vermont','VT','Montpelier','Burlington','44528','South Burlington','21043','Rutland','15630');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Virginia','VA','Richmond','Virginia Beach','453649','Chesapeake','253886','Norfolk','230930');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Washington','WA','Olympia','Seattle','755078','Spokane','229447','Tacoma','222906');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('West Virginia','WV','Charleston','Charleston','46838','Huntington','45325','Morgantown','30429');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Wisconsin','WI','Madison','Milwaukee','561385','Madison','280305','Green Bay','105744');
INSERT INTO `statecaps`(`State_name`, `Abbr`, `Capital`, `Most_pop`, `Population`, `2nd_most_pop`, `2nd_most_pop_pops`, `3rd_most_pop`, `3rd_most_pop_pops`) VALUES ('Wyoming','WY','Cheyenne','Cheyenne','65168','Casper','58720','Gillette','33496')